In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import sklearn

import multiphase_flow_utils
from multiphase_flow_utils import read_and_split_file

BokehUserWarning: The installed bokeh_sampledata version (2024.2) is too old. At least version 2025.0 is needed to run all examples properly. Update with 'pip install -U bokeh_sampledata'.

In [2]:
files_diag = [
    'puros_diagnostic.xlsx',
    'MISTURAS_Final_diagnostic.xlsx',
]
files_proc = [
    'puros_process.xlsx',
    'MISTURAS_Final_process.xlsx',
]

output_file = 'combined_fusion.xlsx'
dataset_nums = ['1','3']

ydata_col = 'Erro ([%])'

In [3]:
dfs_diag = [pd.read_excel(file,) for file in files_diag]
dfs_proc = [pd.read_excel(file,) for file in files_proc]

In [4]:
df_combined_diag = pd.concat(dfs_diag).reset_index().drop(columns='index')
df_combined_proc = pd.concat(dfs_proc).reset_index().drop(columns='index')

#df_combined.to_excel(output_file,index=False)

/tmp/ipykernel_1598012/1241113719.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_combined_diag = pd.concat(dfs_diag).reset_index().drop(columns='index')

In [5]:
df_combined_diag

,media_QMeter (m3_hr),mediana_QMeter (m3_hr),maximo_QMeter (m3_hr),minimo_QMeter (m3_hr),desvio_padrao_QMeter (m3_hr),media_QFlow (m3_hr),mediana_QFlow (m3_hr),maximo_QFlow (m3_hr),minimo_QFlow (m3_hr),desvio_padrao_QFlow (m3_hr),...,mediana_TurbulenceD (%),maximo_TurbulenceD (%),minimo_TurbulenceD (%),desvio_padrao_TurbulenceD (%),media_SwirlAngle (degree),mediana_SwirlAngle (degree),maximo_SwirlAngle (degree),minimo_SwirlAngle (degree),desvio_padrao_SwirlAngle (degree),Erro ([%])
0,3201.005263,3200.3,3240.0,3177.0,19.065748,3201.005263,3200.3,3240.0,3177.0,19.065748,...,2.870,7.70,2.01,1.862999,-5.947368,-6.0,-4,-7,0.621261,-0.175445
1,3205.916667,3201.0,3243.5,3175.7,18.671187,3205.916667,3201.0,3243.5,3175.7,18.671187,...,2.380,6.97,1.17,1.751682,-6.055556,-6.0,-5,-7,0.416176,-0.138311
2,3200.647368,3198.2,3231.3,3178.3,16.436861,3200.647368,3198.2,3231.3,3178.3,16.436861,...,4.330,11.93,1.45,2.885488,-6.157895,-6.0,-5,-8,0.688247,-0.390043
3,3200.663158,3203.3,3232.0,3149.0,22.167173,3200.663158,3203.3,3232.0,3149.0,22.167173,...,5.380,9.93,1.92,2.860632,-6.263158,-6.0,-5,-8,0.733493,-0.486603
4,3200.060000,3195.2,3237.7,3180.6,16.774021,3200.060000,3195.2,3237.7,3180.6,16.774021,...,2.815,14.57,1.13,3.227703,-6.200000,-6.0,-5,-8,0.615587,-0.439279
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
826,78.637500,78.7,79.5,77.8,0.484494,78.637500,78.7,79.5,77.8,0.484494,...,3.325,4.97,2.30,0.699580,-6.208333,-6.0,-6,-7,0.410414,-0.422165
827,79.000000,79.0,80.3,77.8,0.566407,79.000000,79.0,80.3,77.8,0.566407,...,3.130,5.21,2.09,0.827708,-6.280000,-6.0,-6,-7,0.453557,-0.398141
828,78.464000,78.5,79.4,77.7,0.542014,78.464000,78.5,79.4,77.7,0.542014,...,3.720,5.35,2.65,0.766434,-6.240000,-6.0,-6,-7,0.431419,-0.397779
829,78.296000,78.2,79.3,76.7,0.670960,78.296000,78.2,79.3,76.7,0.670960,...,3.430,5.39,2.36,0.725991,-6.280000,-6.0,-6,-7,0.453557,-0.404405
830,78.476000,78.5,79.7,77.2,0.616296,78.476000,78.5,79.7,77.2,0.616296,...,3.400,4.97,1.84,0.784434,-6.440000,-6.0,-6,-7,0.501427,-0.472275

In [6]:
df_combined_proc

,Pressão absoluta ([kPa]),Temp. ([°C]),ρ ([kg/m³]),Visc. ([Pa.s]),Vel (m/s),Reynolds x 10-3,Q Vol ref ([m³/h]),SOS ([m/s]),M ([#]),α·λ ([#]),N2 ([%]),O2 ([%]),Ar ([%]),CO2 ([%]),Erro ([%])
0,1521.954667,27.341667,18.007151,0.000019,28.259443,5466.550481,3201.684933,345.994813,0.081676,0.016289,0.759749,0.200427,0.008898,0.030926,-0.175445
1,1529.152875,28.926250,17.993776,0.000019,28.364601,5460.557838,3212.403961,346.937265,0.081757,0.016232,0.759749,0.200427,0.008898,0.030926,-0.138311
2,1534.497792,30.165000,17.980109,0.000019,28.257918,5418.736185,3208.409435,347.671620,0.081278,0.016190,0.759749,0.200427,0.008898,0.030926,-0.390043
3,1540.225083,31.181667,17.984702,0.000019,28.249785,5404.523279,3210.598304,348.274831,0.081113,0.016142,0.759749,0.200427,0.008898,0.030926,-0.486603
4,1544.858167,32.129792,17.980684,0.000019,28.233138,5387.167264,3207.181116,348.835359,0.080935,0.016105,0.759749,0.200427,0.008898,0.030926,-0.439279
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
826,1506.203561,17.214394,20.887792,0.000017,0.695570,173.672986,79.000620,315.083058,0.002208,0.029820,0.698882,0.003135,0.000179,0.297806,-0.422165
827,1506.100705,17.254167,20.883217,0.000017,0.696666,173.889468,79.106022,315.105670,0.002211,0.029822,0.698882,0.003135,0.000179,0.297806,-0.398141
828,1506.674199,17.286699,20.888779,0.000017,0.693092,173.026793,78.699898,315.123719,0.002199,0.029812,0.698882,0.003135,0.000179,0.297806,-0.397779
829,1508.022340,17.371795,20.901173,0.000017,0.691138,172.598226,78.483262,315.171032,0.002193,0.029788,0.698882,0.003135,0.000179,0.297806,-0.404405
830,1508.244391,17.467308,20.896822,0.000017,0.694522,173.360612,78.921261,315.224996,0.002203,0.029785,0.698882,0.003135,0.000179,0.297806,-0.472275

In [7]:
df_all = pd.concat(
    (
        df_combined_diag,
        df_combined_proc,
    ),
    axis=1,
    #join='outer'
)

In [8]:
df_all.columns.values

<StringArray>
[         'Pressão absoluta ([kPa])',                      'Temp. ([°C])',
                       'ρ ([kg/m³])',                    'Visc. ([Pa.s])',
                         'Vel (m/s)',                   'Reynolds x 10-3',
                'Q Vol ref ([m³/h])',                       'SOS ([m/s])',
                           'M ([#])',                         'α·λ ([#])',
 ...
           'mediana_TurbulenceD (%)',            'maximo_TurbulenceD (%)',
            'minimo_TurbulenceD (%)',     'desvio_padrao_TurbulenceD (%)',
         'media_SwirlAngle (degree)',       'mediana_SwirlAngle (degree)',
        'maximo_SwirlAngle (degree)',        'minimo_SwirlAngle (degree)',
 'desvio_padrao_SwirlAngle (degree)',                        'Erro ([%])']
Length: 591, dtype: str

In [9]:
df_all = df_all.loc[
    :,
    ~df_all.columns.duplicated(keep='last')
]
df_all.to_excel(output_file,index=False)